version: "3.8"

services:
  tribble:
    build: .
    image: tribble
    container_name: tribble
    command: go run main.go
    volumes:
      - .:/go/src/
    working_dir: /go/src/
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      PORT: 80
      DATABASE_URL: postgres://postgres:postgres@db:5432/tribble

  postgres:
    image: postgres:14.2-alpine
    hostname: db
    container_name: tribble_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tribble
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
